spring:
  elasticsearch:
    uris: ["http://localhost:9200"]
    username: elastic
    password: elastic
    connection-timeout: 5s
    socket-timeout: 10s

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: sagittarius-dev
        group: DEFAULT_GROUP
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        username: nacos
        password: nacos
        namespace: sagittarius-dev
        group: DEFAULT_GROUP
        file-extension: yaml
  config:
    import:
      - nacos:sagittarius-common?refreshEnabled=true
      - nacos:sagittarius-article?refreshEnabled=true
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    user:
      type: caffeine
      keyConvertor: fastjson2
      limit: 128
  remote:
    user:
      type: redis.lettuce
      keyConvertor: fastjson2
      broadcastChannel: ${spring.application.name}
      valueEncoder: kryo5
      valueDecoder: kryo5
      cacheNullValue: true
      uri: redis://${redis.password}@${redis.host}:${redis.port}/1?timeout=5s